'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<System.Data.Linq.Mapping.DatabaseAttribute(Name:="R2kdoiMVC")>  _
Partial Public Class r2kdoiMvcAttendanceDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
    Partial Private Sub InsertProgramInstance(instance As Model.Attendance.ProgramInstance)
    End Sub
    Partial Private Sub UpdateProgramInstance(instance As Model.Attendance.ProgramInstance)
    End Sub
    Partial Private Sub DeleteProgramInstance(instance As Model.Attendance.ProgramInstance)
    End Sub
    Partial Private Sub InsertConsumerType(instance As Model.Attendance.ConsumerType)
    End Sub
    Partial Private Sub UpdateConsumerType(instance As Model.Attendance.ConsumerType)
    End Sub
    Partial Private Sub DeleteConsumerType(instance As Model.Attendance.ConsumerType)
    End Sub
    Partial Private Sub InsertLocation(instance As Model.Attendance.Location)
    End Sub
    Partial Private Sub UpdateLocation(instance As Model.Attendance.Location)
    End Sub
    Partial Private Sub DeleteLocation(instance As Model.Attendance.Location)
    End Sub
    Partial Private Sub InsertProgram(instance As Model.Attendance.Program)
    End Sub
    Partial Private Sub UpdateProgram(instance As Model.Attendance.Program)
    End Sub
    Partial Private Sub DeleteProgram(instance As Model.Attendance.Program)
    End Sub
    Partial Private Sub InsertAttendance(instance As Model.Attendance.Attendance)
    End Sub
    Partial Private Sub UpdateAttendance(instance As Model.Attendance.Attendance)
    End Sub
    Partial Private Sub DeleteAttendance(instance As Model.Attendance.Attendance)
    End Sub
    Partial Private Sub InsertAttendanceType(instance As Model.Attendance.AttendanceType)
    End Sub
    Partial Private Sub UpdateAttendanceType(instance As Model.Attendance.AttendanceType)
    End Sub
    Partial Private Sub DeleteAttendanceType(instance As Model.Attendance.AttendanceType)
    End Sub
    Partial Private Sub InsertInfo(instance As Model.Attendance.Info)
    End Sub
    Partial Private Sub UpdateInfo(instance As Model.Attendance.Info)
    End Sub
    Partial Private Sub DeleteInfo(instance As Model.Attendance.Info)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("R2kdoiMVCConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property ProgramInstances() As System.Data.Linq.Table(Of Model.Attendance.ProgramInstance)
		Get
			Return Me.GetTable(Of Model.Attendance.ProgramInstance)
		End Get
	End Property
	
	Public ReadOnly Property vCalendars() As System.Data.Linq.Table(Of Model.Attendance.vCalendar)
		Get
			Return Me.GetTable(Of Model.Attendance.vCalendar)
		End Get
	End Property
	
	Public ReadOnly Property ConsumerTypes() As System.Data.Linq.Table(Of Model.Attendance.ConsumerType)
		Get
			Return Me.GetTable(Of Model.Attendance.ConsumerType)
		End Get
	End Property
	
	Public ReadOnly Property Locations() As System.Data.Linq.Table(Of Model.Attendance.Location)
		Get
			Return Me.GetTable(Of Model.Attendance.Location)
		End Get
	End Property
	
	Public ReadOnly Property Programs() As System.Data.Linq.Table(Of Model.Attendance.Program)
		Get
			Return Me.GetTable(Of Model.Attendance.Program)
		End Get
	End Property
	
	Public ReadOnly Property Attendances() As System.Data.Linq.Table(Of Model.Attendance.Attendance)
		Get
			Return Me.GetTable(Of Model.Attendance.Attendance)
		End Get
	End Property
	
	Public ReadOnly Property AttendanceTypes() As System.Data.Linq.Table(Of Model.Attendance.AttendanceType)
		Get
			Return Me.GetTable(Of Model.Attendance.AttendanceType)
		End Get
	End Property
	
	Public ReadOnly Property Infos() As System.Data.Linq.Table(Of Model.Attendance.Info)
		Get
			Return Me.GetTable(Of Model.Attendance.Info)
		End Get
	End Property
	
	<FunctionAttribute(Name:="dbo.MyCurrentPrograms")>  _
	Public Function MyCurrentPrograms(<Parameter(Name:="InputedBy", DbType:="Int")> ByVal inputedBy As System.Nullable(Of Integer)) As ISingleResult(Of Model.Attendance.ProgramInstance)
		Dim result As IExecuteResult = Me.ExecuteMethodCall(Me, CType(MethodInfo.GetCurrentMethod,MethodInfo), inputedBy)
		Return CType(result.ReturnValue,ISingleResult(Of Model.Attendance.ProgramInstance))
	End Function
End Class

Namespace Model.Attendance
	
	<Table(Name:="Admin.ProgramInstance")>  _
	Partial Public Class ProgramInstance
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _id As Integer
		
		Private _ProgramId As Integer
		
		Private _InstanceName As String
		
		Private _CostCenter As String
		
		Private _SupervisorId As Integer
		
		Private _LocationId As Integer
		
		Private _InActive As System.Nullable(Of Boolean)
		
		Private _Attendances As EntitySet(Of Attendance)
		
		Private _Location As EntityRef(Of Location)
		
		Private _Program As EntityRef(Of Program)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnidChanging(value As Integer)
    End Sub
    Partial Private Sub OnidChanged()
    End Sub
    Partial Private Sub OnProgramIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnProgramIdChanged()
    End Sub
    Partial Private Sub OnInstanceNameChanging(value As String)
    End Sub
    Partial Private Sub OnInstanceNameChanged()
    End Sub
    Partial Private Sub OnCostCenterChanging(value As String)
    End Sub
    Partial Private Sub OnCostCenterChanged()
    End Sub
    Partial Private Sub OnSupervisorIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnSupervisorIdChanged()
    End Sub
    Partial Private Sub OnLocationIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnLocationIdChanged()
    End Sub
    Partial Private Sub OnInActiveChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnInActiveChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			Me._Attendances = New EntitySet(Of Attendance)(AddressOf Me.attach_Attendances, AddressOf Me.detach_Attendances)
			Me._Location = CType(Nothing, EntityRef(Of Location))
			Me._Program = CType(Nothing, EntityRef(Of Program))
			OnCreated
		End Sub
		
		<Column(Storage:="_id", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
		Public Property id() As Integer
			Get
				Return Me._id
			End Get
			Set
				If ((Me._id = value)  _
							= false) Then
					Me.OnidChanging(value)
					Me.SendPropertyChanging
					Me._id = value
					Me.SendPropertyChanged("id")
					Me.OnidChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_ProgramId", DbType:="Int NOT NULL")>  _
		Public Property ProgramId() As Integer
			Get
				Return Me._ProgramId
			End Get
			Set
				If ((Me._ProgramId = value)  _
							= false) Then
					If Me._Program.HasLoadedOrAssignedValue Then
						Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
					End If
					Me.OnProgramIdChanging(value)
					Me.SendPropertyChanging
					Me._ProgramId = value
					Me.SendPropertyChanged("ProgramId")
					Me.OnProgramIdChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_InstanceName", DbType:="VarChar(100) NOT NULL", CanBeNull:=false)>  _
		Public Property InstanceName() As String
			Get
				Return Me._InstanceName
			End Get
			Set
				If (String.Equals(Me._InstanceName, value) = false) Then
					Me.OnInstanceNameChanging(value)
					Me.SendPropertyChanging
					Me._InstanceName = value
					Me.SendPropertyChanged("InstanceName")
					Me.OnInstanceNameChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_CostCenter", DbType:="VarChar(3) NOT NULL", CanBeNull:=false)>  _
		Public Property CostCenter() As String
			Get
				Return Me._CostCenter
			End Get
			Set
				If (String.Equals(Me._CostCenter, value) = false) Then
					Me.OnCostCenterChanging(value)
					Me.SendPropertyChanging
					Me._CostCenter = value
					Me.SendPropertyChanged("CostCenter")
					Me.OnCostCenterChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_SupervisorId", DbType:="Int NOT NULL")>  _
		Public Property SupervisorId() As Integer
			Get
				Return Me._SupervisorId
			End Get
			Set
				If ((Me._SupervisorId = value)  _
							= false) Then
					Me.OnSupervisorIdChanging(value)
					Me.SendPropertyChanging
					Me._SupervisorId = value
					Me.SendPropertyChanged("SupervisorId")
					Me.OnSupervisorIdChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_LocationId", DbType:="Int NOT NULL")>  _
		Public Property LocationId() As Integer
			Get
				Return Me._LocationId
			End Get
			Set
				If ((Me._LocationId = value)  _
							= false) Then
					If Me._Location.HasLoadedOrAssignedValue Then
						Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
					End If
					Me.OnLocationIdChanging(value)
					Me.SendPropertyChanging
					Me._LocationId = value
					Me.SendPropertyChanged("LocationId")
					Me.OnLocationIdChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_InActive", DbType:="Bit")>  _
		Public Property InActive() As System.Nullable(Of Boolean)
			Get
				Return Me._InActive
			End Get
			Set
				If (Me._InActive.Equals(value) = false) Then
					Me.OnInActiveChanging(value)
					Me.SendPropertyChanging
					Me._InActive = value
					Me.SendPropertyChanged("InActive")
					Me.OnInActiveChanged
				End If
			End Set
		End Property
		
		<Association(Name:="ProgramInstance_Attendance", Storage:="_Attendances", ThisKey:="id", OtherKey:="ProgramInstanceId")>  _
		Public Property Attendances() As EntitySet(Of Attendance)
			Get
				Return Me._Attendances
			End Get
			Set
				Me._Attendances.Assign(value)
			End Set
		End Property
		
		<Association(Name:="Location_ProgramInstance", Storage:="_Location", ThisKey:="LocationId", OtherKey:="LocationId", IsForeignKey:=true)>  _
		Public Property Location() As Location
			Get
				Return Me._Location.Entity
			End Get
			Set
				Dim previousValue As Location = Me._Location.Entity
				If ((Object.Equals(previousValue, value) = false)  _
							OrElse (Me._Location.HasLoadedOrAssignedValue = false)) Then
					Me.SendPropertyChanging
					If ((previousValue Is Nothing)  _
								= false) Then
						Me._Location.Entity = Nothing
						previousValue.ProgramInstances.Remove(Me)
					End If
					Me._Location.Entity = value
					If ((value Is Nothing)  _
								= false) Then
						value.ProgramInstances.Add(Me)
						Me._LocationId = value.LocationId
					Else
						Me._LocationId = CType(Nothing, Integer)
					End If
					Me.SendPropertyChanged("Location")
				End If
			End Set
		End Property
		
		<Association(Name:="Program_ProgramInstance", Storage:="_Program", ThisKey:="ProgramId", OtherKey:="ProgramId", IsForeignKey:=true)>  _
		Public Property Program() As Program
			Get
				Return Me._Program.Entity
			End Get
			Set
				Dim previousValue As Program = Me._Program.Entity
				If ((Object.Equals(previousValue, value) = false)  _
							OrElse (Me._Program.HasLoadedOrAssignedValue = false)) Then
					Me.SendPropertyChanging
					If ((previousValue Is Nothing)  _
								= false) Then
						Me._Program.Entity = Nothing
						previousValue.ProgramInstances.Remove(Me)
					End If
					Me._Program.Entity = value
					If ((value Is Nothing)  _
								= false) Then
						value.ProgramInstances.Add(Me)
						Me._ProgramId = value.ProgramId
					Else
						Me._ProgramId = CType(Nothing, Integer)
					End If
					Me.SendPropertyChanged("Program")
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
		
		Private Sub attach_Attendances(ByVal entity As Attendance)
			Me.SendPropertyChanging
			entity.ProgramInstance = Me
		End Sub
		
		Private Sub detach_Attendances(ByVal entity As Attendance)
			Me.SendPropertyChanging
			entity.ProgramInstance = Nothing
		End Sub
	End Class
	
	<Table(Name:="dbo.vCalendar")>  _
	Partial Public Class vCalendar
		
		Private _dt As Date
		
		Private _isWeekday As System.Nullable(Of Boolean)
		
		Private _isHoliday As System.Nullable(Of Boolean)
		
		Private _Y As System.Nullable(Of Short)
		
		Private _FY As System.Nullable(Of Short)
		
		Private _Q As System.Nullable(Of Byte)
		
		Private _M As System.Nullable(Of Byte)
		
		Private _D As System.Nullable(Of Byte)
		
		Private _DW As System.Nullable(Of Byte)
		
		Private _monthname As String
		
		Private _dayname As String
		
		Private _W As System.Nullable(Of Byte)
		
		Private _isoWeek As System.Nullable(Of Byte)
		
		Private _ts As System.Nullable(Of Double)
		
		Private _ds As System.Nullable(Of Boolean)
		
		Public Sub New()
			MyBase.New
		End Sub
		
		<Column(Storage:="_dt", DbType:="SmallDateTime NOT NULL")>  _
		Public Property dt() As Date
			Get
				Return Me._dt
			End Get
			Set
				If ((Me._dt = value)  _
							= false) Then
					Me._dt = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_isWeekday", DbType:="Bit")>  _
		Public Property isWeekday() As System.Nullable(Of Boolean)
			Get
				Return Me._isWeekday
			End Get
			Set
				If (Me._isWeekday.Equals(value) = false) Then
					Me._isWeekday = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_isHoliday", DbType:="Bit")>  _
		Public Property isHoliday() As System.Nullable(Of Boolean)
			Get
				Return Me._isHoliday
			End Get
			Set
				If (Me._isHoliday.Equals(value) = false) Then
					Me._isHoliday = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Y", DbType:="SmallInt")>  _
		Public Property Y() As System.Nullable(Of Short)
			Get
				Return Me._Y
			End Get
			Set
				If (Me._Y.Equals(value) = false) Then
					Me._Y = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_FY", DbType:="SmallInt")>  _
		Public Property FY() As System.Nullable(Of Short)
			Get
				Return Me._FY
			End Get
			Set
				If (Me._FY.Equals(value) = false) Then
					Me._FY = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_Q", DbType:="TinyInt")>  _
		Public Property Q() As System.Nullable(Of Byte)
			Get
				Return Me._Q
			End Get
			Set
				If (Me._Q.Equals(value) = false) Then
					Me._Q = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_M", DbType:="TinyInt")>  _
		Public Property M() As System.Nullable(Of Byte)
			Get
				Return Me._M
			End Get
			Set
				If (Me._M.Equals(value) = false) Then
					Me._M = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_D", DbType:="TinyInt")>  _
		Public Property D() As System.Nullable(Of Byte)
			Get
				Return Me._D
			End Get
			Set
				If (Me._D.Equals(value) = false) Then
					Me._D = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_DW", DbType:="TinyInt")>  _
		Public Property DW() As System.Nullable(Of Byte)
			Get
				Return Me._DW
			End Get
			Set
				If (Me._DW.Equals(value) = false) Then
					Me._DW = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_monthname", DbType:="VarChar(9)")>  _
		Public Property monthname() As String
			Get
				Return Me._monthname
			End Get
			Set
				If (String.Equals(Me._monthname, value) = false) Then
					Me._monthname = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_dayname", DbType:="VarChar(9)")>  _
		Public Property dayname() As String
			Get
				Return Me._dayname
			End Get
			Set
				If (String.Equals(Me._dayname, value) = false) Then
					Me._dayname = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_W", DbType:="TinyInt")>  _
		Public Property W() As System.Nullable(Of Byte)
			Get
				Return Me._W
			End Get
			Set
				If (Me._W.Equals(value) = false) Then
					Me._W = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_isoWeek", DbType:="TinyInt")>  _
		Public Property isoWeek() As System.Nullable(Of Byte)
			Get
				Return Me._isoWeek
			End Get
			Set
				If (Me._isoWeek.Equals(value) = false) Then
					Me._isoWeek = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_ts", DbType:="Float")>  _
		Public Property ts() As System.Nullable(Of Double)
			Get
				Return Me._ts
			End Get
			Set
				If (Me._ts.Equals(value) = false) Then
					Me._ts = value
				End If
			End Set
		End Property
		
		<Column(Storage:="_ds", DbType:="Bit")>  _
		Public Property ds() As System.Nullable(Of Boolean)
			Get
				Return Me._ds
			End Get
			Set
				If (Me._ds.Equals(value) = false) Then
					Me._ds = value
				End If
			End Set
		End Property
	End Class
	
	<Table(Name:="Options.ConsumerType")>  _
	Partial Public Class ConsumerType
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _ConsumerTypeID As Integer
		
		Private _ConsumerType As String
		
		Private _OrderBy As Integer
		
		Private _Infos As EntitySet(Of Info)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnConsumerTypeIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnConsumerTypeIDChanged()
    End Sub
    Partial Private Sub OnConsumerTypeChanging(value As String)
    End Sub
    Partial Private Sub OnConsumerTypeChanged()
    End Sub
    Partial Private Sub OnOrderByChanging(value As Integer)
    End Sub
    Partial Private Sub OnOrderByChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			Me._Infos = New EntitySet(Of Info)(AddressOf Me.attach_Infos, AddressOf Me.detach_Infos)
			OnCreated
		End Sub
		
		<Column(Storage:="_ConsumerTypeID", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
		Public Property ConsumerTypeID() As Integer
			Get
				Return Me._ConsumerTypeID
			End Get
			Set
				If ((Me._ConsumerTypeID = value)  _
							= false) Then
					Me.OnConsumerTypeIDChanging(value)
					Me.SendPropertyChanging
					Me._ConsumerTypeID = value
					Me.SendPropertyChanged("ConsumerTypeID")
					Me.OnConsumerTypeIDChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_ConsumerType", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
		Public Property ConsumerType() As String
			Get
				Return Me._ConsumerType
			End Get
			Set
				If (String.Equals(Me._ConsumerType, value) = false) Then
					Me.OnConsumerTypeChanging(value)
					Me.SendPropertyChanging
					Me._ConsumerType = value
					Me.SendPropertyChanged("ConsumerType")
					Me.OnConsumerTypeChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_OrderBy", DbType:="Int NOT NULL")>  _
		Public Property OrderBy() As Integer
			Get
				Return Me._OrderBy
			End Get
			Set
				If ((Me._OrderBy = value)  _
							= false) Then
					Me.OnOrderByChanging(value)
					Me.SendPropertyChanging
					Me._OrderBy = value
					Me.SendPropertyChanged("OrderBy")
					Me.OnOrderByChanged
				End If
			End Set
		End Property
		
		<Association(Name:="ConsumerType_Info", Storage:="_Infos", ThisKey:="ConsumerTypeID", OtherKey:="ConsumerTypeId")>  _
		Public Property Infos() As EntitySet(Of Info)
			Get
				Return Me._Infos
			End Get
			Set
				Me._Infos.Assign(value)
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
		
		Private Sub attach_Infos(ByVal entity As Info)
			Me.SendPropertyChanging
			entity.ConsumerType = Me
		End Sub
		
		Private Sub detach_Infos(ByVal entity As Info)
			Me.SendPropertyChanging
			entity.ConsumerType = Nothing
		End Sub
	End Class
	
	<Table(Name:="Catalog.Locations")>  _
	Partial Public Class Location
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _LocationId As Integer
		
		Private _LocationName As String
		
		Private _StreetAddress1 As String
		
		Private _StreetAddress2 As String
		
		Private _City As String
		
		Private _Zip As String
		
		Private _County As String
		
		Private _State As String
		
		Private _MainNumber As String
		
		Private _TTyNumber As String
		
		Private _FaxNumber As String
		
		Private _WebAddress As String
		
		Private _ProgramInstances As EntitySet(Of ProgramInstance)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnLocationIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnLocationIdChanged()
    End Sub
    Partial Private Sub OnLocationNameChanging(value As String)
    End Sub
    Partial Private Sub OnLocationNameChanged()
    End Sub
    Partial Private Sub OnStreetAddress1Changing(value As String)
    End Sub
    Partial Private Sub OnStreetAddress1Changed()
    End Sub
    Partial Private Sub OnStreetAddress2Changing(value As String)
    End Sub
    Partial Private Sub OnStreetAddress2Changed()
    End Sub
    Partial Private Sub OnCityChanging(value As String)
    End Sub
    Partial Private Sub OnCityChanged()
    End Sub
    Partial Private Sub OnZipChanging(value As String)
    End Sub
    Partial Private Sub OnZipChanged()
    End Sub
    Partial Private Sub OnCountyChanging(value As String)
    End Sub
    Partial Private Sub OnCountyChanged()
    End Sub
    Partial Private Sub OnStateChanging(value As String)
    End Sub
    Partial Private Sub OnStateChanged()
    End Sub
    Partial Private Sub OnMainNumberChanging(value As String)
    End Sub
    Partial Private Sub OnMainNumberChanged()
    End Sub
    Partial Private Sub OnTTyNumberChanging(value As String)
    End Sub
    Partial Private Sub OnTTyNumberChanged()
    End Sub
    Partial Private Sub OnFaxNumberChanging(value As String)
    End Sub
    Partial Private Sub OnFaxNumberChanged()
    End Sub
    Partial Private Sub OnWebAddressChanging(value As String)
    End Sub
    Partial Private Sub OnWebAddressChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			Me._ProgramInstances = New EntitySet(Of ProgramInstance)(AddressOf Me.attach_ProgramInstances, AddressOf Me.detach_ProgramInstances)
			OnCreated
		End Sub
		
		<Column(Storage:="_LocationId", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
		Public Property LocationId() As Integer
			Get
				Return Me._LocationId
			End Get
			Set
				If ((Me._LocationId = value)  _
							= false) Then
					Me.OnLocationIdChanging(value)
					Me.SendPropertyChanging
					Me._LocationId = value
					Me.SendPropertyChanged("LocationId")
					Me.OnLocationIdChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_LocationName", DbType:="VarChar(50)")>  _
		Public Property LocationName() As String
			Get
				Return Me._LocationName
			End Get
			Set
				If (String.Equals(Me._LocationName, value) = false) Then
					Me.OnLocationNameChanging(value)
					Me.SendPropertyChanging
					Me._LocationName = value
					Me.SendPropertyChanged("LocationName")
					Me.OnLocationNameChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_StreetAddress1", DbType:="VarChar(50)")>  _
		Public Property StreetAddress1() As String
			Get
				Return Me._StreetAddress1
			End Get
			Set
				If (String.Equals(Me._StreetAddress1, value) = false) Then
					Me.OnStreetAddress1Changing(value)
					Me.SendPropertyChanging
					Me._StreetAddress1 = value
					Me.SendPropertyChanged("StreetAddress1")
					Me.OnStreetAddress1Changed
				End If
			End Set
		End Property
		
		<Column(Storage:="_StreetAddress2", DbType:="VarChar(50)")>  _
		Public Property StreetAddress2() As String
			Get
				Return Me._StreetAddress2
			End Get
			Set
				If (String.Equals(Me._StreetAddress2, value) = false) Then
					Me.OnStreetAddress2Changing(value)
					Me.SendPropertyChanging
					Me._StreetAddress2 = value
					Me.SendPropertyChanged("StreetAddress2")
					Me.OnStreetAddress2Changed
				End If
			End Set
		End Property
		
		<Column(Storage:="_City", DbType:="VarChar(50)")>  _
		Public Property City() As String
			Get
				Return Me._City
			End Get
			Set
				If (String.Equals(Me._City, value) = false) Then
					Me.OnCityChanging(value)
					Me.SendPropertyChanging
					Me._City = value
					Me.SendPropertyChanged("City")
					Me.OnCityChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_Zip", DbType:="VarChar(9)")>  _
		Public Property Zip() As String
			Get
				Return Me._Zip
			End Get
			Set
				If (String.Equals(Me._Zip, value) = false) Then
					Me.OnZipChanging(value)
					Me.SendPropertyChanging
					Me._Zip = value
					Me.SendPropertyChanged("Zip")
					Me.OnZipChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_County", DbType:="VarChar(50)")>  _
		Public Property County() As String
			Get
				Return Me._County
			End Get
			Set
				If (String.Equals(Me._County, value) = false) Then
					Me.OnCountyChanging(value)
					Me.SendPropertyChanging
					Me._County = value
					Me.SendPropertyChanged("County")
					Me.OnCountyChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_State", DbType:="VarChar(2)")>  _
		Public Property State() As String
			Get
				Return Me._State
			End Get
			Set
				If (String.Equals(Me._State, value) = false) Then
					Me.OnStateChanging(value)
					Me.SendPropertyChanging
					Me._State = value
					Me.SendPropertyChanged("State")
					Me.OnStateChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_MainNumber", DbType:="VarChar(15)")>  _
		Public Property MainNumber() As String
			Get
				Return Me._MainNumber
			End Get
			Set
				If (String.Equals(Me._MainNumber, value) = false) Then
					Me.OnMainNumberChanging(value)
					Me.SendPropertyChanging
					Me._MainNumber = value
					Me.SendPropertyChanged("MainNumber")
					Me.OnMainNumberChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_TTyNumber", DbType:="VarChar(15)")>  _
		Public Property TTyNumber() As String
			Get
				Return Me._TTyNumber
			End Get
			Set
				If (String.Equals(Me._TTyNumber, value) = false) Then
					Me.OnTTyNumberChanging(value)
					Me.SendPropertyChanging
					Me._TTyNumber = value
					Me.SendPropertyChanged("TTyNumber")
					Me.OnTTyNumberChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_FaxNumber", DbType:="VarChar(15)")>  _
		Public Property FaxNumber() As String
			Get
				Return Me._FaxNumber
			End Get
			Set
				If (String.Equals(Me._FaxNumber, value) = false) Then
					Me.OnFaxNumberChanging(value)
					Me.SendPropertyChanging
					Me._FaxNumber = value
					Me.SendPropertyChanged("FaxNumber")
					Me.OnFaxNumberChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_WebAddress", DbType:="VarChar(50)")>  _
		Public Property WebAddress() As String
			Get
				Return Me._WebAddress
			End Get
			Set
				If (String.Equals(Me._WebAddress, value) = false) Then
					Me.OnWebAddressChanging(value)
					Me.SendPropertyChanging
					Me._WebAddress = value
					Me.SendPropertyChanged("WebAddress")
					Me.OnWebAddressChanged
				End If
			End Set
		End Property
		
		<Association(Name:="Location_ProgramInstance", Storage:="_ProgramInstances", ThisKey:="LocationId", OtherKey:="LocationId")>  _
		Public Property ProgramInstances() As EntitySet(Of ProgramInstance)
			Get
				Return Me._ProgramInstances
			End Get
			Set
				Me._ProgramInstances.Assign(value)
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
		
		Private Sub attach_ProgramInstances(ByVal entity As ProgramInstance)
			Me.SendPropertyChanging
			entity.Location = Me
		End Sub
		
		Private Sub detach_ProgramInstances(ByVal entity As ProgramInstance)
			Me.SendPropertyChanging
			entity.Location = Nothing
		End Sub
	End Class
	
	<Table(Name:="[Case].Programs")>  _
	Partial Public Class Program
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _ProgramId As Integer
		
		Private _Acronym As String
		
		Private _ProgramName As String
		
		Private _ProgramDescription As String
		
		Private _PoTypeId As Integer
		
		Private _InActive As Boolean
		
		Private _ProgramInstances As EntitySet(Of ProgramInstance)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnProgramIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnProgramIdChanged()
    End Sub
    Partial Private Sub OnAcronymChanging(value As String)
    End Sub
    Partial Private Sub OnAcronymChanged()
    End Sub
    Partial Private Sub OnProgramNameChanging(value As String)
    End Sub
    Partial Private Sub OnProgramNameChanged()
    End Sub
    Partial Private Sub OnProgramDescriptionChanging(value As String)
    End Sub
    Partial Private Sub OnProgramDescriptionChanged()
    End Sub
    Partial Private Sub OnPoTypeIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnPoTypeIdChanged()
    End Sub
    Partial Private Sub OnInActiveChanging(value As Boolean)
    End Sub
    Partial Private Sub OnInActiveChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			Me._ProgramInstances = New EntitySet(Of ProgramInstance)(AddressOf Me.attach_ProgramInstances, AddressOf Me.detach_ProgramInstances)
			OnCreated
		End Sub
		
		<Column(Storage:="_ProgramId", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
		Public Property ProgramId() As Integer
			Get
				Return Me._ProgramId
			End Get
			Set
				If ((Me._ProgramId = value)  _
							= false) Then
					Me.OnProgramIdChanging(value)
					Me.SendPropertyChanging
					Me._ProgramId = value
					Me.SendPropertyChanged("ProgramId")
					Me.OnProgramIdChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_Acronym", DbType:="VarChar(15) NOT NULL", CanBeNull:=false)>  _
		Public Property Acronym() As String
			Get
				Return Me._Acronym
			End Get
			Set
				If (String.Equals(Me._Acronym, value) = false) Then
					Me.OnAcronymChanging(value)
					Me.SendPropertyChanging
					Me._Acronym = value
					Me.SendPropertyChanged("Acronym")
					Me.OnAcronymChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_ProgramName", DbType:="VarChar(50) NOT NULL", CanBeNull:=false)>  _
		Public Property ProgramName() As String
			Get
				Return Me._ProgramName
			End Get
			Set
				If (String.Equals(Me._ProgramName, value) = false) Then
					Me.OnProgramNameChanging(value)
					Me.SendPropertyChanging
					Me._ProgramName = value
					Me.SendPropertyChanged("ProgramName")
					Me.OnProgramNameChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_ProgramDescription", DbType:="VarChar(300) NOT NULL", CanBeNull:=false)>  _
		Public Property ProgramDescription() As String
			Get
				Return Me._ProgramDescription
			End Get
			Set
				If (String.Equals(Me._ProgramDescription, value) = false) Then
					Me.OnProgramDescriptionChanging(value)
					Me.SendPropertyChanging
					Me._ProgramDescription = value
					Me.SendPropertyChanged("ProgramDescription")
					Me.OnProgramDescriptionChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_PoTypeId", DbType:="Int NOT NULL")>  _
		Public Property PoTypeId() As Integer
			Get
				Return Me._PoTypeId
			End Get
			Set
				If ((Me._PoTypeId = value)  _
							= false) Then
					Me.OnPoTypeIdChanging(value)
					Me.SendPropertyChanging
					Me._PoTypeId = value
					Me.SendPropertyChanged("PoTypeId")
					Me.OnPoTypeIdChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_InActive", DbType:="Bit NOT NULL")>  _
		Public Property InActive() As Boolean
			Get
				Return Me._InActive
			End Get
			Set
				If ((Me._InActive = value)  _
							= false) Then
					Me.OnInActiveChanging(value)
					Me.SendPropertyChanging
					Me._InActive = value
					Me.SendPropertyChanged("InActive")
					Me.OnInActiveChanged
				End If
			End Set
		End Property
		
		<Association(Name:="Program_ProgramInstance", Storage:="_ProgramInstances", ThisKey:="ProgramId", OtherKey:="ProgramId")>  _
		Public Property ProgramInstances() As EntitySet(Of ProgramInstance)
			Get
				Return Me._ProgramInstances
			End Get
			Set
				Me._ProgramInstances.Assign(value)
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
		
		Private Sub attach_ProgramInstances(ByVal entity As ProgramInstance)
			Me.SendPropertyChanging
			entity.Program = Me
		End Sub
		
		Private Sub detach_ProgramInstances(ByVal entity As ProgramInstance)
			Me.SendPropertyChanging
			entity.Program = Nothing
		End Sub
	End Class
	
	<Table(Name:="Admin.Attendances")>  _
	Partial Public Class Attendance
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _AttendanceId As Integer
		
		Private _ProgramInstanceId As Integer
		
		Private _RegistrarNo As String
		
		Private _AttendanceTypeId As Integer
		
		Private _Clock As Date
		
		Private _InputedBy As Integer
		
		Private _Ed As Date
		
		Private _ProgramInstance As EntityRef(Of ProgramInstance)
		
		Private _AttendanceType As EntityRef(Of AttendanceType)
		
		Private _Info As EntityRef(Of Info)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnAttendanceIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnAttendanceIdChanged()
    End Sub
    Partial Private Sub OnProgramInstanceIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnProgramInstanceIdChanged()
    End Sub
    Partial Private Sub OnRegistrarNoChanging(value As String)
    End Sub
    Partial Private Sub OnRegistrarNoChanged()
    End Sub
    Partial Private Sub OnAttendanceTypeIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnAttendanceTypeIdChanged()
    End Sub
    Partial Private Sub OnClockChanging(value As Date)
    End Sub
    Partial Private Sub OnClockChanged()
    End Sub
    Partial Private Sub OnInputedByChanging(value As Integer)
    End Sub
    Partial Private Sub OnInputedByChanged()
    End Sub
    Partial Private Sub OnEdChanging(value As Date)
    End Sub
    Partial Private Sub OnEdChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			Me._ProgramInstance = CType(Nothing, EntityRef(Of ProgramInstance))
			Me._AttendanceType = CType(Nothing, EntityRef(Of AttendanceType))
			Me._Info = CType(Nothing, EntityRef(Of Info))
			OnCreated
		End Sub
		
		<Column(Storage:="_AttendanceId", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
		Public Property AttendanceId() As Integer
			Get
				Return Me._AttendanceId
			End Get
			Set
				If ((Me._AttendanceId = value)  _
							= false) Then
					Me.OnAttendanceIdChanging(value)
					Me.SendPropertyChanging
					Me._AttendanceId = value
					Me.SendPropertyChanged("AttendanceId")
					Me.OnAttendanceIdChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_ProgramInstanceId", DbType:="Int NOT NULL")>  _
		Public Property ProgramInstanceId() As Integer
			Get
				Return Me._ProgramInstanceId
			End Get
			Set
				If ((Me._ProgramInstanceId = value)  _
							= false) Then
					If Me._ProgramInstance.HasLoadedOrAssignedValue Then
						Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
					End If
					Me.OnProgramInstanceIdChanging(value)
					Me.SendPropertyChanging
					Me._ProgramInstanceId = value
					Me.SendPropertyChanged("ProgramInstanceId")
					Me.OnProgramInstanceIdChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_RegistrarNo", DbType:="VarChar(6) NOT NULL", CanBeNull:=false)>  _
		Public Property RegistrarNo() As String
			Get
				Return Me._RegistrarNo
			End Get
			Set
				If (String.Equals(Me._RegistrarNo, value) = false) Then
					If Me._Info.HasLoadedOrAssignedValue Then
						Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
					End If
					Me.OnRegistrarNoChanging(value)
					Me.SendPropertyChanging
					Me._RegistrarNo = value
					Me.SendPropertyChanged("RegistrarNo")
					Me.OnRegistrarNoChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_AttendanceTypeId", DbType:="Int NOT NULL")>  _
		Public Property AttendanceTypeId() As Integer
			Get
				Return Me._AttendanceTypeId
			End Get
			Set
				If ((Me._AttendanceTypeId = value)  _
							= false) Then
					If Me._AttendanceType.HasLoadedOrAssignedValue Then
						Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
					End If
					Me.OnAttendanceTypeIdChanging(value)
					Me.SendPropertyChanging
					Me._AttendanceTypeId = value
					Me.SendPropertyChanged("AttendanceTypeId")
					Me.OnAttendanceTypeIdChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_Clock", DbType:="DateTime NOT NULL")>  _
		Public Property Clock() As Date
			Get
				Return Me._Clock
			End Get
			Set
				If ((Me._Clock = value)  _
							= false) Then
					Me.OnClockChanging(value)
					Me.SendPropertyChanging
					Me._Clock = value
					Me.SendPropertyChanged("Clock")
					Me.OnClockChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_InputedBy", DbType:="Int NOT NULL")>  _
		Public Property InputedBy() As Integer
			Get
				Return Me._InputedBy
			End Get
			Set
				If ((Me._InputedBy = value)  _
							= false) Then
					Me.OnInputedByChanging(value)
					Me.SendPropertyChanging
					Me._InputedBy = value
					Me.SendPropertyChanged("InputedBy")
					Me.OnInputedByChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_Ed", DbType:="DateTime NOT NULL")>  _
		Public Property Ed() As Date
			Get
				Return Me._Ed
			End Get
			Set
				If ((Me._Ed = value)  _
							= false) Then
					Me.OnEdChanging(value)
					Me.SendPropertyChanging
					Me._Ed = value
					Me.SendPropertyChanged("Ed")
					Me.OnEdChanged
				End If
			End Set
		End Property
		
		<Association(Name:="ProgramInstance_Attendance", Storage:="_ProgramInstance", ThisKey:="ProgramInstanceId", OtherKey:="id", IsForeignKey:=true)>  _
		Public Property ProgramInstance() As ProgramInstance
			Get
				Return Me._ProgramInstance.Entity
			End Get
			Set
				Dim previousValue As ProgramInstance = Me._ProgramInstance.Entity
				If ((Object.Equals(previousValue, value) = false)  _
							OrElse (Me._ProgramInstance.HasLoadedOrAssignedValue = false)) Then
					Me.SendPropertyChanging
					If ((previousValue Is Nothing)  _
								= false) Then
						Me._ProgramInstance.Entity = Nothing
						previousValue.Attendances.Remove(Me)
					End If
					Me._ProgramInstance.Entity = value
					If ((value Is Nothing)  _
								= false) Then
						value.Attendances.Add(Me)
						Me._ProgramInstanceId = value.id
					Else
						Me._ProgramInstanceId = CType(Nothing, Integer)
					End If
					Me.SendPropertyChanged("ProgramInstance")
				End If
			End Set
		End Property
		
		<Association(Name:="AttendanceType_Attendance", Storage:="_AttendanceType", ThisKey:="AttendanceTypeId", OtherKey:="AttendanceTypeId", IsForeignKey:=true)>  _
		Public Property AttendanceType() As AttendanceType
			Get
				Return Me._AttendanceType.Entity
			End Get
			Set
				Dim previousValue As AttendanceType = Me._AttendanceType.Entity
				If ((Object.Equals(previousValue, value) = false)  _
							OrElse (Me._AttendanceType.HasLoadedOrAssignedValue = false)) Then
					Me.SendPropertyChanging
					If ((previousValue Is Nothing)  _
								= false) Then
						Me._AttendanceType.Entity = Nothing
						previousValue.Attendances.Remove(Me)
					End If
					Me._AttendanceType.Entity = value
					If ((value Is Nothing)  _
								= false) Then
						value.Attendances.Add(Me)
						Me._AttendanceTypeId = value.AttendanceTypeId
					Else
						Me._AttendanceTypeId = CType(Nothing, Integer)
					End If
					Me.SendPropertyChanged("AttendanceType")
				End If
			End Set
		End Property
		
		<Association(Name:="Info_Attendance", Storage:="_Info", ThisKey:="RegistrarNo", OtherKey:="RegistrarNo", IsForeignKey:=true)>  _
		Public Property Info() As Info
			Get
				Return Me._Info.Entity
			End Get
			Set
				Dim previousValue As Info = Me._Info.Entity
				If ((Object.Equals(previousValue, value) = false)  _
							OrElse (Me._Info.HasLoadedOrAssignedValue = false)) Then
					Me.SendPropertyChanging
					If ((previousValue Is Nothing)  _
								= false) Then
						Me._Info.Entity = Nothing
						previousValue.Attendances.Remove(Me)
					End If
					Me._Info.Entity = value
					If ((value Is Nothing)  _
								= false) Then
						value.Attendances.Add(Me)
						Me._RegistrarNo = value.RegistrarNo
					Else
						Me._RegistrarNo = CType(Nothing, String)
					End If
					Me.SendPropertyChanged("Info")
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
	End Class
	
	<Table(Name:="Options.AttendanceTypes")>  _
	Partial Public Class AttendanceType
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _AttendanceTypeId As Integer
		
		Private _AttendanceType As String
		
		Private _IsAbsent As Integer
		
		Private _Attendances As EntitySet(Of Attendance)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnAttendanceTypeIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnAttendanceTypeIdChanged()
    End Sub
    Partial Private Sub OnAttendanceTypeChanging(value As String)
    End Sub
    Partial Private Sub OnAttendanceTypeChanged()
    End Sub
    Partial Private Sub OnIsAbsentChanging(value As Integer)
    End Sub
    Partial Private Sub OnIsAbsentChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			Me._Attendances = New EntitySet(Of Attendance)(AddressOf Me.attach_Attendances, AddressOf Me.detach_Attendances)
			OnCreated
		End Sub
		
		<Column(Storage:="_AttendanceTypeId", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
		Public Property AttendanceTypeId() As Integer
			Get
				Return Me._AttendanceTypeId
			End Get
			Set
				If ((Me._AttendanceTypeId = value)  _
							= false) Then
					Me.OnAttendanceTypeIdChanging(value)
					Me.SendPropertyChanging
					Me._AttendanceTypeId = value
					Me.SendPropertyChanged("AttendanceTypeId")
					Me.OnAttendanceTypeIdChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_AttendanceType", DbType:="VarChar(10) NOT NULL", CanBeNull:=false)>  _
		Public Property AttendanceType() As String
			Get
				Return Me._AttendanceType
			End Get
			Set
				If (String.Equals(Me._AttendanceType, value) = false) Then
					Me.OnAttendanceTypeChanging(value)
					Me.SendPropertyChanging
					Me._AttendanceType = value
					Me.SendPropertyChanged("AttendanceType")
					Me.OnAttendanceTypeChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_IsAbsent", DbType:="Int NOT NULL")>  _
		Public Property IsAbsent() As Integer
			Get
				Return Me._IsAbsent
			End Get
			Set
				If ((Me._IsAbsent = value)  _
							= false) Then
					Me.OnIsAbsentChanging(value)
					Me.SendPropertyChanging
					Me._IsAbsent = value
					Me.SendPropertyChanged("IsAbsent")
					Me.OnIsAbsentChanged
				End If
			End Set
		End Property
		
		<Association(Name:="AttendanceType_Attendance", Storage:="_Attendances", ThisKey:="AttendanceTypeId", OtherKey:="AttendanceTypeId")>  _
		Public Property Attendances() As EntitySet(Of Attendance)
			Get
				Return Me._Attendances
			End Get
			Set
				Me._Attendances.Assign(value)
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
		
		Private Sub attach_Attendances(ByVal entity As Attendance)
			Me.SendPropertyChanging
			entity.AttendanceType = Me
		End Sub
		
		Private Sub detach_Attendances(ByVal entity As Attendance)
			Me.SendPropertyChanging
			entity.AttendanceType = Nothing
		End Sub
	End Class
	
	<Table(Name:="Consumers.Info")>  _
	Partial Public Class Info
		Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
		
		Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
		
		Private _RegistrarNo As String
		
		Private _SSN As String
		
		Private _REF As String
		
		Private _ConsumerTypeId As Integer
		
		Private _LastName As String
		
		Private _MiddleName As String
		
		Private _FirstName As String
		
		Private _Inputedby As Integer
		
		Private _ED As Date
		
		Private _UD As Date
		
		Private _Permilink As String
		
		Private _PrefixId As System.Nullable(Of Integer)
		
		Private _SufixId As System.Nullable(Of Integer)
		
		Private _FlagForHr As System.Nullable(Of Boolean)
		
		Private _Attendances As EntitySet(Of Attendance)
		
		Private _ConsumerType As EntityRef(Of ConsumerType)
		
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnRegistrarNoChanging(value As String)
    End Sub
    Partial Private Sub OnRegistrarNoChanged()
    End Sub
    Partial Private Sub OnSSNChanging(value As String)
    End Sub
    Partial Private Sub OnSSNChanged()
    End Sub
    Partial Private Sub OnREFChanging(value As String)
    End Sub
    Partial Private Sub OnREFChanged()
    End Sub
    Partial Private Sub OnConsumerTypeIdChanging(value As Integer)
    End Sub
    Partial Private Sub OnConsumerTypeIdChanged()
    End Sub
    Partial Private Sub OnLastNameChanging(value As String)
    End Sub
    Partial Private Sub OnLastNameChanged()
    End Sub
    Partial Private Sub OnMiddleNameChanging(value As String)
    End Sub
    Partial Private Sub OnMiddleNameChanged()
    End Sub
    Partial Private Sub OnFirstNameChanging(value As String)
    End Sub
    Partial Private Sub OnFirstNameChanged()
    End Sub
    Partial Private Sub OnInputedbyChanging(value As Integer)
    End Sub
    Partial Private Sub OnInputedbyChanged()
    End Sub
    Partial Private Sub OnEDChanging(value As Date)
    End Sub
    Partial Private Sub OnEDChanged()
    End Sub
    Partial Private Sub OnUDChanging(value As Date)
    End Sub
    Partial Private Sub OnUDChanged()
    End Sub
    Partial Private Sub OnPermilinkChanging(value As String)
    End Sub
    Partial Private Sub OnPermilinkChanged()
    End Sub
    Partial Private Sub OnPrefixIdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnPrefixIdChanged()
    End Sub
    Partial Private Sub OnSufixIdChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSufixIdChanged()
    End Sub
    Partial Private Sub OnFlagForHrChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnFlagForHrChanged()
    End Sub
    #End Region
		
		Public Sub New()
			MyBase.New
			Me._Attendances = New EntitySet(Of Attendance)(AddressOf Me.attach_Attendances, AddressOf Me.detach_Attendances)
			Me._ConsumerType = CType(Nothing, EntityRef(Of ConsumerType))
			OnCreated
		End Sub
		
		<Column(Storage:="_RegistrarNo", DbType:="VarChar(6) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
		Public Property RegistrarNo() As String
			Get
				Return Me._RegistrarNo
			End Get
			Set
				If (String.Equals(Me._RegistrarNo, value) = false) Then
					Me.OnRegistrarNoChanging(value)
					Me.SendPropertyChanging
					Me._RegistrarNo = value
					Me.SendPropertyChanged("RegistrarNo")
					Me.OnRegistrarNoChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_SSN", DbType:="NVarChar(11) NOT NULL", CanBeNull:=false)>  _
		Public Property SSN() As String
			Get
				Return Me._SSN
			End Get
			Set
				If (String.Equals(Me._SSN, value) = false) Then
					Me.OnSSNChanging(value)
					Me.SendPropertyChanging
					Me._SSN = value
					Me.SendPropertyChanged("SSN")
					Me.OnSSNChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_REF", DbType:="VarChar(20)")>  _
		Public Property REF() As String
			Get
				Return Me._REF
			End Get
			Set
				If (String.Equals(Me._REF, value) = false) Then
					Me.OnREFChanging(value)
					Me.SendPropertyChanging
					Me._REF = value
					Me.SendPropertyChanged("REF")
					Me.OnREFChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_ConsumerTypeId", DbType:="Int NOT NULL")>  _
		Public Property ConsumerTypeId() As Integer
			Get
				Return Me._ConsumerTypeId
			End Get
			Set
				If ((Me._ConsumerTypeId = value)  _
							= false) Then
					If Me._ConsumerType.HasLoadedOrAssignedValue Then
						Throw New System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
					End If
					Me.OnConsumerTypeIdChanging(value)
					Me.SendPropertyChanging
					Me._ConsumerTypeId = value
					Me.SendPropertyChanged("ConsumerTypeId")
					Me.OnConsumerTypeIdChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_LastName", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
		Public Property LastName() As String
			Get
				Return Me._LastName
			End Get
			Set
				If (String.Equals(Me._LastName, value) = false) Then
					Me.OnLastNameChanging(value)
					Me.SendPropertyChanging
					Me._LastName = value
					Me.SendPropertyChanged("LastName")
					Me.OnLastNameChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_MiddleName", DbType:="NVarChar(50)")>  _
		Public Property MiddleName() As String
			Get
				Return Me._MiddleName
			End Get
			Set
				If (String.Equals(Me._MiddleName, value) = false) Then
					Me.OnMiddleNameChanging(value)
					Me.SendPropertyChanging
					Me._MiddleName = value
					Me.SendPropertyChanged("MiddleName")
					Me.OnMiddleNameChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_FirstName", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
		Public Property FirstName() As String
			Get
				Return Me._FirstName
			End Get
			Set
				If (String.Equals(Me._FirstName, value) = false) Then
					Me.OnFirstNameChanging(value)
					Me.SendPropertyChanging
					Me._FirstName = value
					Me.SendPropertyChanged("FirstName")
					Me.OnFirstNameChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_Inputedby", DbType:="Int NOT NULL")>  _
		Public Property Inputedby() As Integer
			Get
				Return Me._Inputedby
			End Get
			Set
				If ((Me._Inputedby = value)  _
							= false) Then
					Me.OnInputedbyChanging(value)
					Me.SendPropertyChanging
					Me._Inputedby = value
					Me.SendPropertyChanged("Inputedby")
					Me.OnInputedbyChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_ED", DbType:="DateTime NOT NULL")>  _
		Public Property ED() As Date
			Get
				Return Me._ED
			End Get
			Set
				If ((Me._ED = value)  _
							= false) Then
					Me.OnEDChanging(value)
					Me.SendPropertyChanging
					Me._ED = value
					Me.SendPropertyChanged("ED")
					Me.OnEDChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_UD", DbType:="DateTime NOT NULL")>  _
		Public Property UD() As Date
			Get
				Return Me._UD
			End Get
			Set
				If ((Me._UD = value)  _
							= false) Then
					Me.OnUDChanging(value)
					Me.SendPropertyChanging
					Me._UD = value
					Me.SendPropertyChanged("UD")
					Me.OnUDChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_Permilink", DbType:="VarChar(255) NOT NULL", CanBeNull:=false)>  _
		Public Property Permilink() As String
			Get
				Return Me._Permilink
			End Get
			Set
				If (String.Equals(Me._Permilink, value) = false) Then
					Me.OnPermilinkChanging(value)
					Me.SendPropertyChanging
					Me._Permilink = value
					Me.SendPropertyChanged("Permilink")
					Me.OnPermilinkChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_PrefixId", DbType:="Int")>  _
		Public Property PrefixId() As System.Nullable(Of Integer)
			Get
				Return Me._PrefixId
			End Get
			Set
				If (Me._PrefixId.Equals(value) = false) Then
					Me.OnPrefixIdChanging(value)
					Me.SendPropertyChanging
					Me._PrefixId = value
					Me.SendPropertyChanged("PrefixId")
					Me.OnPrefixIdChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_SufixId", DbType:="Int")>  _
		Public Property SufixId() As System.Nullable(Of Integer)
			Get
				Return Me._SufixId
			End Get
			Set
				If (Me._SufixId.Equals(value) = false) Then
					Me.OnSufixIdChanging(value)
					Me.SendPropertyChanging
					Me._SufixId = value
					Me.SendPropertyChanged("SufixId")
					Me.OnSufixIdChanged
				End If
			End Set
		End Property
		
		<Column(Storage:="_FlagForHr", DbType:="Bit")>  _
		Public Property FlagForHr() As System.Nullable(Of Boolean)
			Get
				Return Me._FlagForHr
			End Get
			Set
				If (Me._FlagForHr.Equals(value) = false) Then
					Me.OnFlagForHrChanging(value)
					Me.SendPropertyChanging
					Me._FlagForHr = value
					Me.SendPropertyChanged("FlagForHr")
					Me.OnFlagForHrChanged
				End If
			End Set
		End Property
		
		<Association(Name:="Info_Attendance", Storage:="_Attendances", ThisKey:="RegistrarNo", OtherKey:="RegistrarNo")>  _
		Public Property Attendances() As EntitySet(Of Attendance)
			Get
				Return Me._Attendances
			End Get
			Set
				Me._Attendances.Assign(value)
			End Set
		End Property
		
		<Association(Name:="ConsumerType_Info", Storage:="_ConsumerType", ThisKey:="ConsumerTypeId", OtherKey:="ConsumerTypeID", IsForeignKey:=true)>  _
		Public Property ConsumerType() As ConsumerType
			Get
				Return Me._ConsumerType.Entity
			End Get
			Set
				Dim previousValue As ConsumerType = Me._ConsumerType.Entity
				If ((Object.Equals(previousValue, value) = false)  _
							OrElse (Me._ConsumerType.HasLoadedOrAssignedValue = false)) Then
					Me.SendPropertyChanging
					If ((previousValue Is Nothing)  _
								= false) Then
						Me._ConsumerType.Entity = Nothing
						previousValue.Infos.Remove(Me)
					End If
					Me._ConsumerType.Entity = value
					If ((value Is Nothing)  _
								= false) Then
						value.Infos.Add(Me)
						Me._ConsumerTypeId = value.ConsumerTypeID
					Else
						Me._ConsumerTypeId = CType(Nothing, Integer)
					End If
					Me.SendPropertyChanged("ConsumerType")
				End If
			End Set
		End Property
		
		Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
		
		Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
		
		Protected Overridable Sub SendPropertyChanging()
			If ((Me.PropertyChangingEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
			End If
		End Sub
		
		Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
			If ((Me.PropertyChangedEvent Is Nothing)  _
						= false) Then
				RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
			End If
		End Sub
		
		Private Sub attach_Attendances(ByVal entity As Attendance)
			Me.SendPropertyChanging
			entity.Info = Me
		End Sub
		
		Private Sub detach_Attendances(ByVal entity As Attendance)
			Me.SendPropertyChanging
			entity.Info = Nothing
		End Sub
	End Class
End Namespace
